#!/usr/bin/env python
from includes.daemonize import startstop
from server import main, bye

from sys import stderr as sys_stderr


startstop(stdout='/dev/null', 
          stderr=sys_stderr, 
          pidfile='/tmp/monserver.pid',
          on_exit=bye)
main()

